pipeline {
    agent any 
    stages {
        stage ('checkout') {
            steps {
                script{
                    git "https://github.com/ravindrasinghh/google-compute.git"
                }
            }
        }
    }
        stage ('init') {
            steps {
                sh 'ls;terraform init -input=false'
            }
        }
}