pipeline {
    parameters {
       choice(name: 'environment', choices: ['dev','qa','stage','prod'], description: 'Setting this will deploy the services on selected environment')    
       choice(name: 'branch_name', choices: ['master','development'], description: 'Select branch name')
       booleanParam(name: 'autoApprove', defaultValue: false, description: 'Automatically run apply after generating plan?')
    }
    agent any 
    options {
      buildDiscarder(logRotator(numToKeepStr: "10"))
  }
    stages {
        stage ('checkout') {
            steps {
                script{
                    git (credentialsId: 'git', url: 'https://github.com/ravindrasinghh/google-compute',branch: '${branch_name}')
                }
            }
        }
        stage ('terraform init') {
            steps {
                dir("terraform") {
                sh 'terraform init -input=false'
                sh 'pwd;cd /var/lib/jenkins/workspace/private/terraform'
                sh 'rm -rf .terraform/*'
                }
            }
        }
        stage ('terraform plan') {
            steps {
                dir("terraform") {
                sh 'terraform init'
                sh 'terraform workspace select ${environment}'
                sh 'ls'    
                sh 'terraform plan -input=false -out tfplan'
                }
            }
        }
        stage ('terraform apply') {
            steps {
                dir("terraform") {
                sh 'ls'
                }
            }
        }
    }
}
